name: publish

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-20.04

        environment:
            name: pypi

        strategy:
          matrix:
            python-version: ["3.10"]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: update package manager & install python3 environment
              run: |
                pip install poetry
                poetry install

            - name: publish on pypi
              run: poetry run alfred publish:twine
